sButtons/sbuttons

- index.html
Updated Google font URL to include swap.
Issue:
> changed Google font URL to include swap

- assets/css/index.css
- index.html
Resolves issue #6 to make download link smaller on devices up to 767px.
> Reduce download link to 1.15rem font size at xs screen size (<768px).

- index.html
Add how to use sidebar
Issue: Add link to "How to Use" sectio  in sidebar
> add how to use sidebar

- assets/css/index.css
- index.html
I use some trick css by adding padding-top and margin-top, so when we click the sidebar, the content will fully covered
Issue: Navigating onclick sidebar bug
> Sidebar scroll

- assets/css/index.css
- assets/js/index.js
- index.html
Scroll to top button added , visit https://pratyush-saxena.github.io/sbuttons/ to see the changes
Issue: #27 resolved
> scroll-top btn added

- assets/css/index.css
- assets/css/variables.css
> CSS custom property added

- assets/js/index.js
Substract viewport and bounds height with margin header. 
Issue: Active sidebar not pointing on right content
> fixing sidebar active content

- README.md
- index.html
* Add a note about font awesome cdn in README.md
* Add a note section about font awesome cdn in index.html 
Issue: Add a note about using font awesome for some buttons #38
> Add a note about using font awesome

- assets/js/index.js
Reduced the scroll-to-top Speed for mobile (small) Screens <= 640 Pixels.
Tested it on my mobile Phone, feels good to me.
This is my first PR, any feedback is welcome
Issue: #50
> Scroll-Up Speed slower on mobile Screens

- .all-contributorsrc
- CONTRIBUTERS.md
- README.md
- assets/js/index.js
- index.html
- Added Bootstrap Tooltip, triggered by click on class names below the Button & automatically hides after a interval of 1500ms.
Attached Screenshot is showing tooltip triggered on click. (See first button in the image)
> added tooltip- on copying class names

- index.html
Signed-off-by: Ashley Pean <pean.ashley@gmail.com>
Issue: Updated text in the How to Use section
> Updated How To Use section

- assets/css/index.css
- index.html
After clicking the buttons an default box-shadow was added which was not looking good.
Issue:
> removed default box-shadow

- assets/css/index.css
- assets/css/sidebar.css
- assets/js/index.js
- index.html
Added hamburger for mobile devices
Issue: #7
> Added hamburger 

- README.md
Issue: "implementedto"
This is fixed to "implemented to".
> fixed a typo on README.md

- assets/css/index.css
For button of class .clipboard, set outline: 0; on :focus
The same has been done.
Issue:
> outline edit made

- assets/css/index.css
- assets/css/variables.css
- assets/js/index.js
- index.html
Added light/dark mode.
Added some CSS for dark theme and JS functions for switching modes.
Issue: #97
> Added light/dark mode [Issue #97]

- assets/js/buttons-examples.js
Issue: Sorted buttons elements alphabetically  #99
sorted manually.
> sorted 'var buttons[]'

- assets/css/sidebar.css
> Add cursor: pointer to .sidebar-toggler

- assets/css/sidebar.css
it positions the close icon near the end of sidebar by adjusting the padding
Issue: close #121
> close-sidebar fix

- assets/css/sidebar.css
Changed background color for .sidebar a:before
Issue:
https://github.com/shahednasser/sbuttons/issues/122
> change bg color

- assets/css/index.css
adding overflow on small device and some style, check this out.
Issue: Overflowing items in sidebar not showing on small devices#86
> add overflowing y auto on small devives

- assets/css/index.css
- assets/js/buttons-examples.js
- index.html
tet
Issue: close button on small device
> Close button smalldevice

- index.html
Added a link to submit new button ideas in index.html
Issue: #135
> feat: add a link to submit new button ideas

- README.md
Issue: #172 Fixes link to CONTRIBUTORS.md
Corrected the link from CONTRIBUTERS.md to CONTRIBUTORS.md
> Fixes #172 link to CONTRIBUTORS.md

- assets/js/index.js
@shahednasser i have resolved issue #85 ...pls review this pr
> issue #85 resolved

- assets/css/index.css
Issue: #177 edited index.css for changing font size for device width less than 786px
> Fixes #177 added changed font size for .toggle-theme in index.css

- index.html
On the last two code blocks in the "How to Use" section on the website, I replaced the single quotations with double quotations.
> Replaced single quotations with double quotations in code block in website. #165

- BUTTON_IDEAS.md
Adding this button idea that I'd like to implement
Issue: #96
> Neumorphic button idea

- assets/js/index.js
> Moved showing/hiding sidebar to toggleSidebar function

- assets/css/index.css
- assets/js/index.js
- index.html
Fixing this issue: https://github.com/shahednasser/sbuttons/issues/133
I added two buttons to the header under the subtitle text, the download button is an animated click with a white background and black text, the documentation link button has a white background with black text and border.
I also added css to index.css for overriding the button colors to be white (along with comments for other contributors), I'm more than happy to make a permanent white class for all the buttons though!
✨
> Header download & documentation buttons (animated click & outline)

- assets/css/index.css
Changed the color of .button-caption-sub in dark mode 
Issue: #114 #147
> Change color of .button-caption-sub in dark mode

- BUTTON_IDEAS.md
> Added new category for button idea regarding login | signup

- BUTTON_IDEAS.md
- CONTRIBUTING.md
I've refactored the button ideas list to a table, and I've also added the instruction on how to go about contributing for contributors
Issue: #208
> refactor button ideas list to table

- assets/css/index.css
- index.html
Added a link to the logo in the navbar to the same page,i.e, index.html.
Also changed color of navbar logo back to main color in css file.
Issue: #215
> Resolved: Add a link to the logo in the navbar #215

- README.md
Issue:
I resolved the file name issue in readme.md for ALL contributors tag
> fixed : Fix Contributors link in the badge in README #234

- BUTTON_IDEAS.md
Added a new button idea with the requirements.
> Added a new button idea

- assets/css/index.css
> Add block button ideas

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/animated/_neon.less
- src/sbuttons.less
@shahednasser I have added the support for different neon colour combinations.
Resolves: #226
> Added different neon colours effect

- BUTTON_IDEAS.md
> Done changes

- dist/sbuttons.css
- src/components/icon/_like.less
I decreasse keyframe, and add more duration for animating like button, I try to make it simple.. how do you think ?
Issue:
> fixing like button animation

- assets/css/index.css
- index.html
It looks like this...
@shahednasser Can you check if its all right or not now?
Resolves: #252
> Changed UI of the Banner

- BUTTON_IDEAS.md
- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_animated.less
- src/components/_basic.less
- src/components/animated/_ripple.less
@shahednasser  I have added Ripple type button as mentioned in [BUTTON_IDEAS.md](https://github.com/shahednasser/sbuttons/blob/master/BUTTON_IDEAS.md)
Issue: #1
> Added Ripple Type Button

- assets/css/index.css
Issue: Changed the fonts for the "Download" and "Documentation" links in the header to "Syne" in `assets/css/index.html` (UPDATE)
> Changed headers to Syne Font (Update)

- assets/css/index.css
- assets/css/sidebar.css
• Improved font-family, font-size, letter-spacing for the nav .items in the sidebar !
-imported Google Font "Merienda"
• Increased space between nav .items in sidebar and improved transition speed of the underline coming on hover by 0.1s
Issue: Change in Sidebar Nav .items Font Family ! #247
Text in the Nav. items of sidebar looks really congested and font family also looks not so aesthetic.
• Attaching the before after look of the sidebar .nav items below ⬇
> Sidebar nav. items' design fix

- index.html
Link to local contributors.md file prompts to download it. Also Information with syntax would be inconvenient for a user to to look into. So Link to contributors.md page on GitHub is added.
> Link to CONTRIBUTORS.md added in the footer

- BUTTON_IDEAS.md
- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_animated.less
- src/components/animated/_splash.less
> added splash button

- BUTTON_IDEAS.md
> new button idea

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_social.less
- src/components/social/_apple.less
> login with apple button added

- BUTTON_IDEAS.md
> Chat box Button Idea added

- assets/css/index.css
margin-bottom of navbar changed from 2em to 1 em.
> changed navbar margin-bottom

- assets/css/index.css
Fixed the position issue of header icons in screens with width <= 368px
Fixes: #300
> Fixed responsiveness issues #300

- BUTTON_IDEAS.md
I add a new button idea. It is about a play game button which has a game controller shape similar to the PS4 one.
> add-button-idea

- dist/sbuttons.css
- src/components/_social.less
changed font size of .social-btn from 1rem to 1.2rem
#Issue: #314
> change font-size of .social-btn

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_animated.less
- src/components/animated/_snake.less
> Snake border issue

- BUTTON_IDEAS.md
added multiple ideas for social buttons.
1. neon glow button with social icon only.
2. neon glow button with social icon and name.
> added social button ideas

- BUTTON_IDEAS.md
> Added strikethrough to the finished buttons

- BUTTON_IDEAS.md
- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_icon.less
- src/components/icon/_chat.less
> Added Chat Box Button

- BUTTON_IDEAS.md
added animated button name
Issue:
> Added Animated Gradient border Button idea

- BUTTON_IDEAS.md
Changed the column header "status" to "Status" in all tables in BUTTON_IDEAS.md
> Capitalized "status" in BUTTON_IDEAS.md

- BUTTON_IDEAS.md
Fixes #375 
Fixed style table structure.
The last row in the style table was not alligned and was appearing outside the table.
> Revamped BUTTON_IDEAS.MD

- .github/ISSUE_TEMPLATE/bug_report.md
> Added Steps

- BUTTON_IDEAS.md
added  "Bring to Top Button" and "Text Size +/-(adjustment) Button" 
Issue:
> Added Bring to Top & Text Size button ideas

- BUTTON_IDEAS.md
> Added Atom Button

- BUTTON_IDEAS.md
> Add a Loading button

- assets/css/index.css
- index.html
Animated gradient for footer is added. Both the timing and colour of the animation can be modified at `assets/css/index.css`.
> sButtons footer design

- dist/sbuttons.css
- src/components/_hover.less
- src/sbuttons.less
White button now exhibits hover button behaviour. 
Red and Yellow hover buttons tweaked for clarity.
Issue:
> Modified Hover Button Behaviour

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_icon.less
- src/components/animated/_bounce.less
- src/components/icon/_scroll-to-top.less
Added Scroll-to-Top icon without text.
Issue:
> scroll to top icon

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_dashed.less
- src/sbuttons.less
I have added a dashed style button type
Issue: Add New Buttons
> Added a dashed type button

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_special.less
- src/components/special/_retro.less
- src/sbuttons.less
I have added `_retro.less` as a special button type, along with the special button directory. 
Also added Google Font, and made changes in the button-example.js file.
> Added retro.less to 'special' buttons folder

- .github/workflows/preview.yml
> Update preview.yml for comment action

- .github/workflows/preview.yml
> Preview action update

- assets/css/index.css
Added min-height to body > .container
Issue: #512
> Added min-height

- dist/sbuttons.css
- src/components/_social.less
- src/components/social/_google.less
- src/components/social/_instagram.less
- src/components/social/_linkedin.less
- src/components/social/_twitter.less
- src/components/social/_weibo.less
> [Fix] Align Social Media Icons in Buttons #513

- CONTRIBUTING.md
> Fixed the typo (Normat to Normal)

- CONTRIBUTING.md
Reverts shahednasser/sbuttons#530
> Revert "Fixed the typo (Normat to Normal)"

- getStarted.html
Added hr under Disabled Buttons section on Get started page
Issue: #528
> added hr under disabled buttons

- CONTRIBUTING.md
- README.md
Documentation changed - modified README.md and CONTRIBUTING.md as specified in issue
Issue: #535
> Changed text in Button Ideas section

- assets/js/buttons-examples.js
Added comments to the [buttons-examples.js](https://github.com/shahednasser/sbuttons/blob/master/assets/js/buttons-examples.js) according to the JSDoc conventions.
Issue: #480
> Added JSDoc documentation to the buttons-examples.js

- assets/css/index.css
- assets/js/index.js
- getStarted.html
- index.html
Added the animation to the navbar on scroll. And fixed a minor issue of sidebar links.
Issue: #550
> Added animation to the navbar and fixed Minor sidebar link issue

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_icon.less
- src/components/icon/_star.less
> Add star button

- assets/js/buttons-examples.js
Added JSDoc documentation to buttons list object
Issue: #480
> Added JSDoc for the buttons list objects

- getStarted.html
Adding example of block-btn, so the user can preview before they want to implement
Issue:
> Block Button Example

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_social.less
- src/components/social/_microsoft.less
- src/components/social/_reddit.less
> added microsoft and reddit social buttons

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_special.less
- src/components/icon/_star.less
- src/components/special/_rounded-top.less
I added a new special button called rounded top.
The new class is _rounded-top.less, and I added it to buttons-examples.js and _special.less.
Issue: Add New Buttons
> Rounded top

- assets/js/buttons-examples.js
> rename button labels

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_icon.less
- src/components/icon/_thumbsup.less
This pull request will add a simple basic THUMBS-UP button.
> Added a thumbs up button class.

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_animated.less
- src/components/_basic.less
- src/components/animated/_diagonalBackground.less
Issue:  [BUTTON IDEA]: Diagonally appearing background on hover #482
> Diagonal background animation

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_social.less
- src/components/social/_discord.less
Issue: 
#643 
Created `_discord.less` file and added the button to website via `assets/js/button-examples.js`
> Add Discord Button to the website 

- dist/sbuttons.css
- src/components/animated/_ripple.less
Simplified the selector while refactoring code
Issue: 657
> Refactored _ripple.less

- dist/sbuttons.css
- src/components/animated/_splash.less
#659 : Refactor splash.less to use less features instead of CSS
> refactor _splash.less

- src/components/animated/_snake.less
The code of animated snake button has been reduced, updating the nesting of it
Issue: #658
> Update snake-btn nesting

- dist/sbuttons.css
- src/components/animated/_neon.less
> refactored _neon.less

- dist/sbuttons.css
- src/components/animated/_diagonalBackground.less
> refactor diagonal bg file

- assets/css/index.css
- index.html
Changed down-link class to transparent on hover and added custom css to maintain its position removed down-link class from download button because it's not required anymore
Issue:#699
> updated class on download button and added some custom css

- dist/sbuttons.css
- src/components/icon/_setting.less
removed `position:absolute` in file `src/components/icon/_setting.less` 
Issue: #689
> setting button is modified

- .github/workflows/compile.yml
Issue: This resolves #708 
Added an action that runs `npm run compile` whenever there is a pull request with changes to the `src` directory.
@shahednasser
> Compile action for pull requests

- getStarted.html
- index.html
Created a link to the homepage at the logo of sButtons in the navbar.
Please let me know if any changes are expected.
Regards,
Akanksha.
> Added link to logo in navbar

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_animated.less
- src/components/animated/_flash.less
Added a new **animated button**: **_flash button_**
Issue:  #732
> Added flash button animation

- getStarted.html
Fixed typos in getStarted.html
> Fixed typos.

- dist/sbuttons.css
- src/components/animated/_bounce.less
Issue:
https://github.com/sButtons/sbuttons/issues/751
> enhaced bounce animation of Animated buttons

- assets/js/index.js
adding offsetFooter on isOnScreen function for check bounds.bottom , please check it out.
Issue: Get Started Page - Sidebar Icon Button not active
> fixing last menu sidebar not active

- assets/css/index.css
I have made  fixes to the nav bar items which were hidden for mobile view.<br>
Benefit of change: now user on mobile can also switch to dark or day themes.
to do this i have done resizing of icons for width: 410, 311, 265 and 225
Issue: mentioned in #735
> made changes to navbar problem #735

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_special.less
- src/components/special/_code-btn.less
Added a new button style under Special buttons called Code Button
Issue: Add New Buttons #1
>  added new  "code" button

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/icon/_star.less
I added the active class and mixin for star icon button.
It's same as #754 but I can't change the branch of pull request so I make a new one.
Issue: #750
> feat: Add active state for star button (#750)

- README.md
- getStarted.html
> added npm links (Issue #742)

- dist/sbuttons.css
- src/components/animated/_shine.less
> Shine Button Effects in Shine.less

- assets/js/buttons-examples.js
Issue: Place "Snake Border" button in the correct alphabetical order under Animated #841
Changes: Modify the snake border button placement in assets/js/buttons-examples.js
label: first-timers-only
> Place SnakeBorder button in the correct alphabetical order

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_animated.less
- src/components/animated/_spring.less
Added new button animation style
.spring-btn
-give button a spring like animation when hover on.
> Added spring-btn animation style

- assets/js/buttons-examples.js
Very minor change on documentation on website.
https://github.com/sButtons/sbuttons/issues/849
Issue:
> Removed extra dot as per #849

- assets/css/index.css
- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/styles/_key.less
Key Button Updated
Issue: Improve Key Button
> key button updated

- assets/css/index.css
overlappings of buttons 
Issue:resolved issue #871
> fixed overlappings of buttons on home page

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_styles.less
- src/components/styles/_striped.less
Added the Striped style to Button Styles. 
Issue:
[BUTTON IDEA]: Striped Button #877
> added striped button under Button Styles

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/animated/_fill.less
added sideways fill button
this button fill color starting from the center and goes on both side in animated type like door
Issue:  #880
> Sideways fill button added

- dist/sbuttons.css
- src/components/styles/_gradient.less
- Changes gradient animation
- Decrease box-shadow 
As animating gradient in not possible directly so I have used this workaround [link](https://codepen.io/pirrera/pen/bqVeGx?editors=1100)
Demo:  
Issue: #885
> Change gradient button transition and box shadow

- getStarted.html
Moved some headings and buttons outside of redundant .text divs. Resulting in correct application of fonts.
Issue: #890
> Standardized the Font of Headings in 'getStarted.html'

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_animated.less
- src/components/animated/_papercurl.less
Added a button that curls on hover
Issue:
No Issues
> Added a button that curls on hover

- assets/js/buttons-examples.js
- debug.log
- dist/sbuttons.css
- src/components/_special.less
- src/components/special/_rainbow-border.less
> Added rainbow border button

- dist/sbuttons.css
- src/components/animated/_liquid.less
Scrolling issue in scrolling button is solved in this..
**how this looked before \ how this will look**
Issue:
scrolling liquid button solved
> scrolling liquid button issue solved

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_social.less
- src/components/social/_bitbucket.less
- src/components/social/_gitlab.less
-  added GitLab and Bitbucket to social icons 
- Created ```_gitlab.less``` and ```_bitbucket.less```  file and added the button to website via ```assets/js/button-examples.js```
Issue: #936
> added gitlab and bitbucket to social

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_icon.less
- src/components/icon/_hatch.less
> Added: icon hatch button.

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/social/_steam.less
Issue:
A new button idea of adding "Login with  Steam" button in the social buttons type implemented .
> login with steam button added

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_animated.less
- src/components/animated/_atom.less
Added animated button.
Referred to issue #918
Issue:
> Atom button

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_animated.less
- src/components/animated/_rainbow.less
rainbow-btn is added
Issue:
New button added
>  rainbow button added

- .github/workflows/greet_messege.yml
Made changes int greet_message.yml review it. Please allow to make pr on master.
Issue: #738
> Test welcome action

- .github/workflows/greet_messege.yml
Issue: fixing as per explained in #991
> fixed typo in new greeting.yml file

- documentation.html
- examples.html
- index.html
There an issue created to change the spelling of sButton on the example page and this what was fix in this pull request
Issue: https://github.com/sButtons/sbuttons/issues/1021
> Fix to sButton Spelling

- assets/js/buttons-examples.js
- Added Rounded button for Neon border button ( issue #1005 )
> Add Rounded button for Neon border button

- dist/sbuttons.css
- src/components/animated/_loading-btn.less
Issue: #1003
@HADES-01 noted that the animations in select loading buttons is twitchy and does not seem to animate as expected.
This PR makes minor edits to timing and animation settings for all loading button types except the `spin` type with the goal of smoothing out animations.
**Original:**
**What this PR proposes:**
Resolves #1003
> fix: make loading animations smoother

- assets/css/index.css
- assets/js/index.js
Fix Color Theme is not changing on Home page ( issue #1041 )
- Unable to find element with class ```.main-head``` in index page was causing the issue. Resolved it checking length of collection returned by query selector, ```$(".main-head").length```.
- Also added checking condition to footer element, which uses ```$.fn.isOnScreen``` for future prevention.
- Fix Dark mode text color change ( issue #1042 )
> Fix Color Theme is not changing on Home page

- assets/css/main.css
I have fixed below Issue. In CSS border radius Top-right and Bottom-right should be 0px.
Issue:
https://github.com/sButtons/sbuttons/issues/1035
> [Mani]-Fixed CSS hover issue in Dark Mode

- assets/css/main.css
closes https://github.com/sButtons/sbuttons/issues/1016
> style: change tab's text to white when hover in dark mode

- assets/css/main.css
closes https://github.com/sButtons/sbuttons/issues/1015
> style: change scroll to top color to white on dark mode

- assets/css/variables.css
> changed footer colour to #233240

- assets/css/header.css
> fixed links style

- assets/css/header.css
- documentation.html
- examples.html
This PR reveals the nav logo on smaller displays.
Closes #1007
> fix: Fix nav logo on smaller displays

- index.html
> Added copy to clipboard

- documentation.html
- examples.html
- index.html
Inside "index.html", "document.html" and "examples.html" added <a> tag to sButton icon with a href to "index.html".
Issue: Fix for issue #1085 
sButton logo on top left now redirects to "index.html" when clicked.
> Fix for issue 1085

- assets/css/main.css
Added `z-index: 20` to main.css
(footer.css had `z-index: 12`)
Issue: #1010
> z-index of scroll-top button 

- index.html
> Changed text in home page

- dist/sbuttons.css
- src/components/styles/_dashed.less
Changed black button to white button and text color of white button
from black to white in dark mode.
Issue:  #1014
> Added dark mode support for dashed button.

- dist/sbuttons.css
- src/components/animated/_diagonalBackground.less
- src/components/animated/_expanding.less
- src/components/animated/_fill.less
Issue: #1022 
Added animated class to Diagonal Background, Expanding Border, Fill Buttons All Types. Please see the 5 demos below for Diagonal Background, Expanding Border, Fill Buttons - Down, Fill Buttons - Left, and Fill Buttons - Sideways.
> Add animated class to Diagonal Background, Expanding Border, Fill Buttons All Types

- dist/sbuttons.css
- src/components/animated/_colored-on-hover.less
- src/components/icon/_hatch.less
Changed the text color to white when dark mode (black and white button)
Issue: #1014
> Add darkmode support for colored on hover button + add dark-mode class to hatch button

- assets/css/main.css
- assets/js/index.js
Sidebar anomaly in documentation and example page
Issue: #1149
> fix for Sidebar anomaly in documentation and example page #1149

- dist/sbuttons.css
- src/components/_social.less
Issue:The issue of Login With Steam button
Expected Behaviour:
> Added Steam Css

- dist/sbuttons.css
- src/components/animated/_transparent.less
I am resubmitting it with the required change
> added dark mode to black color for transparent on hover

- README.md
- documentation.html
This pull request adds the use of the toggle button as checkboxes and radio buttons into the documentation page as well as documents the same in the readme.md file.
Issue: Add documentation about toggle button #983
> Toggle Button Documentation

- dist/sbuttons.css
- src/components/animated/_atom.less
Issue: #1114 
Please see the demo below. Let me know if I misunderstood the expected behavior.
> fix bug in atom

- dist/sbuttons.css
- src/components/animated/_arrow.less
- src/components/animated/_neon.less
> add animated class to Neon and Next

- dist/sbuttons.css
- src/components/animated/_nudge.less
- src/components/animated/_vibrate.less
> Add animated to nudge and vibrate

- dist/sbuttons.css
- src/components/animated/_pudding.less
- src/components/animated/_pulse.less
> Add animated class to Pulse and Pudding

- examples.html
Issue: #1194 
now the pr has right commit.
> #1194 copy button not working in example page : fixed

- dist/sbuttons.css
- src/components/animated/_arrow.less
- src/components/animated/_papercurl.less
> Add animated class to Paper Curl and Previous

- documentation.html
> issue #1196 : radio button example fix

- assets/css/header.css
- index.html
> darkmode button in mobile view

- assets/js/buttons-examples.js
- dist/sbuttons.css
- src/components/_animated.less
- src/components/animated/_striped-animated.less
I have added animation to the striped button class, as was requested in #1223 
The animation runs infinitely. 
Here is a demo:
> ![captured](https://user-images.githubusercontent.com/43912470/105613408-508ac680-5de8-11eb-8334-5ff57b8c381f.gif)
The button works well in dark mode as well.
Please offer suggestions, if any.
> Added Animated Striped Button

- assets/css/footer.css
fixed width of the footer section
Issue: #1226
> fixed  horizontal scrolling of website  issue for small devices #1226

- dist/sbuttons.css
- package-lock.json
- src/components/animated/_transparent.less
- src/components/special/_rainbow-border.less
I've added a new "animated class" to an animated button named as "Transparent On Hover"
Issue: #1022
> Added a animated class to 'Transparent On Hover' Button

- assets/css/documentation.css
I have  made  the max width of .instruction-block 700px to match the code block.
Issue:#1244
> Made the max width of .instruction-block 700px to match the code block

- documentation.html
- index.html
I have updated the cdn links throughout the whole website
Issue:1247
> updated cdn links

- documentation.html
Updated website documentation under NPM to reflect recent changes made in the README.
Also corrected a small mistake.
Issue:#1268
> Issue #1268: Updated Website Documentation

- assets/css/documentation.css
- assets/css/examples.css
- assets/css/main.css
- assets/js/buttons-examples.js
- assets/js/index.js
- documentation.html
@shahednasser  I'm very sorry I have to open a new pull request for pr #1274 since  instead of syncying  my fork repo to the master I deleted it instead and fork the repo again thereby losing my branch. I'm very sorry for the trouble :)
Issue:#1260
> Added Copy link to documentation and example page

- dist/sbuttons.css
- src/components/styles/_glossy-btn.less
added transition all .2s to glossy button
> add transition to glossy button

- assets/css/documentation.css
- assets/css/examples.css
- assets/css/footer.css
- assets/css/header.css
- assets/css/index.css
- assets/css/main.css
- documentation.html
- examples.html
- index.html
Updated font Syne to Montserrat. 
Issue: #1240
> Add new font

- dist/sbuttons.css
- src/components/styles/_rounded-top.less
> resolved : Added transition to rounded buttons #1264

- dist/sbuttons.css
- src/components/animated/_invert.less
I have added 'animated' class to Invert
Issue: #1022
> Add animated class to Invert 

- assets/css/header.css
- assets/js/index.js
- index.html
> Added dropdown menu in home page

- dist/sbuttons.css
- src/components/animated/_hinge.less
Hinge is now triggered by hover and adding animated class.
Issue:
https://github.com/sButtons/sbuttons/issues/1022
> Update hinge animation

- dist/sbuttons.css
- src/components/animated/_flash.less
I have added animated class to flash button .
Issue:#1022
> added animated class to flash button

- dist/sbuttons.css
- src/components/animated/_ripple.less
- src/components/animated/_scale.less
I have added animated class to ripple and scale button .
Issue:#1022
> Added animated class to scale and ripple button

- dist/sbuttons.css
- src/components/animated/_liquid.less
- src/components/animated/_rainbow.less
I added the animated class to the Liquid and the Rainbow button. I saw that the hover effect was unique for each color button. I updated this, so this is now only specified one time in the CSS file.
Issue: #1022
> Added animated class to Liquid and Rainbow button

- website/src/components/Header.js
- website/src/pages/Documentation/index.js
Increased the size of div to accommodate the texts without line break in small devices
> Drop Down Menu width in small devices

- README.md
- website/src/components/SidebarLink.js
- website/src/pages/Documentation/index.js
Added documentation for animated buttons to README and Documentation page
> Added documentation for animated buttons

- dist/sbuttons.css
- src/components/_basic.less
> Several different options for rounded-btn

- website/package.json
Dependency sbuttons references the git repo sButtons/sbuttons now instead of the latest npm package release
Issue: #1383 Change the website to use the CSS in the repository
> referencing files in repository

- dist/sbuttons.css
- src/_variables.less
- src/components/special/_toggle.less
Hi Shahed, this is my proposed fix for issue #1378 .
I ran tests on my end, but please let me know if I have any mistakes in the code.
As for the hover: issue in pull requests, I was previously using Windows 10, build 19043 which caused problems with prettier AND the lessc.
I redid the same changes on Ubuntu 20.04 and there seemed to be no problem. I think you were right about the OS having an effect.
Thanks for all the input! This project has been very valuable for a beginner like me.
> Toggle button visibility firefox fixed #1378

- README.md
Tried to resolve issue  #1398. Please suggest the changes if required.
Thanks
> Changes in ReadME

- website/src/index.css
> changed the min-height of content class

- website/public/index.html
Improved the description meta tag
fixed issue #1387 
Issue:
> Improved the description meta tag for index.html

- website/src/pages/Documentation/index.js
Issue:
The car name 'Bugatti' was spelled 'Budgati'
I fixed this typo :)
> Fix a typo

- README.md
Issue: There was an error/ typo in the README file
> fixed an typo/error in readme

- website/src/data/buttons.json
Reordered links in alphabetical order.
Issue: #1478
> Reordered links in alphabetical order.

- website/src/components/Hero.js
- website/src/index.css
Created new ID  heading in      (website/src/index.css)
few minor changes in (website/src/components/Hero.js)
> Changes to heading

- website/src/components/Sidebar.js
- website/src/pages/Examples/index.js
I have updated `Sidebar.js` to include a search box which can quickly filter the `SideBarLink` items. I choose to make this addition directly in the Sidebar component as it is very closely tied with the `children` prop of `Sidebar.js`.
Additionally, I made a small change to the Examples page such that all direct children of the `Sidebar` component are `SidebarLink` components to ensure full compatibility with the new search feature.
Please test the search and let me know what you think, I hope you find it useful!
Issue: https://github.com/sButtons/sbuttons/issues/1446
> Addition of sidebar search filter for SideBarLink items

- README.md
- package-lock.json
- website/package-lock.json
Issue: Redirect to ERROR page when click on license button in readme file
> FIx # 1610 Issue
