sButtons/sbuttons

index.html
added seperator after "How to use section" and "Basic Buttons"
issue #17 
Issue:
=> added seperator after "How to use section" and "Basic Buttons"

index.html
Replaced "Download" in the navbar with an font awesome _fa-file-download_ icon.
Issue: #88
=> Replaced download text link with icon [Issue #88]

assets/css/index.css, index.html
**Additions:**
- Disable text selection on the _.logo h1_ which is a child of _.navbar_ and _.content_
- Files modified: _index.html_ and _assets/css/index.css_
- Tested in the following browsers: Chrome 85, Firefox 80, Opera 70, Edge 85
Issue:
Relates to issue #71, **specs**:
Add a rule to .logo h1 to disable user selection. Make sure to add the changes to assets/css/index.css
=> Disable text selection issue #71

CONTRIBUTORS.md, index.html
renamed CONTRIBUTORS md file as it was misspelled, also changed the single quotes to double quotes in the last two code blocks of How To Use section
Issue: #165
=> Fixed typo in CONTRIBUTORS

assets/js/index.js, index.html
The download button now download a file with all the code instead of opening the raw github page.
<a download / wasn't working as raw github page isn't considered like a file , so i came up with using JS & fetch API.
Issue: #158
=> Fixed Download Button on website

assets/css/index.css, assets/js/buttons-examples.js, index.html
Added a loading wheel that spins while buttons are loading and disappears they have loaded.
Followed [this tutorial](https://www.w3schools.com/howto/howto_css_loader.asp) to create the wheel. 
Issue: #484
=> Show loading wheel before button examples appear

dist/sbuttons.css, src/components/_social.less
The icons of the social buttons which are also block buttons have been moved a bit left towards the "Login with.." text.
Files changed : dist/sbuttons.css and src/components/_social.less
Issue: #309
=> social block buttons moved towards login text

dist/sbuttons.css, src/components/animated/_fill.less
Fix the white/transparent line on the right of the button for buttons with a fill animation and rounded corners (.fill-color-btn .rounded-btn) on Safari (webkit) on iOs and macOs.
Issue: #54
=> Fix fill-animation on rounded buttons

assets/css/index.css, assets/css/sidebar.css, assets/js/buttons-examples.js
Issue: #564 
@shahednasser 
At first, when I launched the website on my PC, The links were not overlapping the footer, that was because the content wasn't much then, so I went on to add additional button examples in the `button-examples.js` file so I'd be able to see the error.
I fixed this error by adding a fixed width to the submenu links of all the button examples and allowing them to overflow, thus, the scrollbar you see..
Kindly check the GIF below to see it in action.
=> fix overlaying scrollbar

dist/sbuttons.css, src/components/styles/_glossy-btn.less
I added a "border: none" to the glossy-btn class because I noticed the glossy buttons had a border that cut off the glossy white part of the button. When I saw them for the first time that part kind of threw me off so that's why I changed it to this.
=> Changed glossy button border

assets/js/buttons-examples.js
I have ordered button styles as requested per issue "Sort Button Styles in Alphabetical order" 
(On the website, Button Styles are not sorted in alphabetical order. You just need to make changes in assets/js/buttons-examples.js. No changes to any design.)
Issue #793
=> Re-ordered button styles alphabetically

assets/js/buttons-examples.js
Deleted "Buttons"/"Button" from labels in buttons-example.js
Issue: #830
=> deleted "Buttons" from label

.github/workflows/greet_messege.yml
resolved this issue : Add an action on pull request and new issue for an automatic reply #738 
Issue: feature request as in #738 
**make it hacktoberfest**
=> added the greeting message file

assets/js/buttons-examples.js
**Removed the repeated outline button** from Button Styles section from side navbar and updated according to **alphabetical order.**
**Issue #824 :** There are 2 outline button section in the website . They both are same .
=> Removed two outline buttons

assets/js/buttons-examples.js, getStarted.html
I noticed that `button-examples.js` is also called for `getStarted.html`. This script makes up the sample buttons for the home page, and as far as I'm concerned, it's not needed on the "[Getting Started](https://sbuttons.github.io/sbuttons/getStarted.html)" page.
At the same time a simple measurement shows that the script runs for about 500 ms for each page load:
```js
$(document).ready(function () {
start = Date.now();
// original code is here
console.log( 'Unclaimed work lasted', Date.now() - start, 'ms' );
});
```
Due to this I've made two changes:
1. Commented out the call to the script. Now it is obvious that the script is not involved in this file.
2. Transfered to the beginning of the script the initialization of the pointers to the sidebar and to the block of the buttons. If one …
=> Do not launch the button examples script on the "Get Started" page

assets/js/buttons-examples.js, dist/sbuttons.css, src/components/animated/_splash.less
As mentioned , I have removed the borders from the animated-splash-button.
Issue:
**How the button looked before \ How it will look**
=> Removed the borders from splash button

dist/sbuttons.css, src/components/special/_neumorphic.less
Made the neumorphic button shadows darker and highlights dimmer when the data-theme is set to dark.
Fixes: #902 
**Before -**
**After -**
=> Better Neumorphic Buttons in Darkmode

assets/js/index.js
Fix #862. 
Commits:
1. Show all accessors instead of the parent only.
The key point is to make visible the entire chain of nested blocks in a menu of 3 or more levels.
2. Rename auxiliary variables so that their meaning becomes clear even without analyzing the HTML layout.
3. Reorganize the "if else" block to make its logic more obvious.
4. Remove the unused `return false;` statement:
- the function has no other `return` instructions;
- without a `return` statement, the function returns the value` null`, which plays almost the same role in comparison operations as `false`;
- the function is called from two places in the code without any interest in its result.
=> Fix #862. Show all levels in the sidebar menu

getStarted.html
Currently the subtitle in "Usage" and the subsection in "Base Icon Button" have the same identifiers. The second identifier is better to change.
=> Fix the duplicate `block` id on the `Get Started` page

README.md
Issue:  #938
Fixed missing syntax-highlighting in the ```code``` blocks of the README.md file.
=> fix: README.md, added missing syntax highlighting for codeblocks.

index.html
examples URL now opens examples page in new tab.
Issue: #994
=> example URL in Footer fixed

index.html
This PR will replace wrong link in `index.html`.
Closes #993
=> fix: Replace link to docs

assets/css/documentation.css, assets/css/examples.css
fixes: #1006
The overlapping of text in examples and documentation pages in mobile view has been fixed.
=> fixed overlapping of text in mobile view

dist/sbuttons.css, src/components/animated/_flash.less
closes #1019
I think 0.6s is the best option. I made a gif for other speeds I have tested as well:
0.5s
0.6s
0.8s
1s
=> style: change animation duration for flash button

assets/css/examples.css
Reduced margin below extra-large buttons to make visual grouping more obvious.
Issue: https://github.com/sButtons/sbuttons/issues/1020
=> Reduced margin below extra-large buttons

dist/sbuttons.css, src/components/animated/_atom.less
Issue: #1022 - atom button
Adds `.animated` class with continuous loop of the existing hover animation.
Demo with `.animated` added to blue button:
=> Feat: add animated class to atom button

dist/sbuttons.css, src/components/animated/_papercurl.less
Addresses issue #1017. 
Made so it when in dark mode, papercurl uses dark mode's background color instead of white. 
While not transparent, it provides the desired look. 
Before the background was explicitly set to white. I followed this same pattern by doing this. 
Is this workaround okay?
Thank you
=> Used dark papercurl when in dark theme.

documentation.html
=> Link to the example page rather than then the home page from Documentation page and remove target blank because a new tab should not be opened

assets/css/documentation.css, assets/css/header.css
Fixed overflowing buttons 
and also removed `.sbtn {
font-size: 1rem;
}
` in documentation.css page because it was overwriting the css which was to be applied.
Issue:#1079
=> Fixed overflowing of buttons on index, documentation and example page

dist/sbuttons.css, src/components/icon/_hatch.less
Fixed bug on the hatch buttons. Before the icon perspective was not following the perspective of the button when on focus.
Issue: Hatch buttons perspective bug #1072
=> fix hatch btn perspective #1072

assets/js/buttons-examples.js
Inside "buttons-examples.js", updated text for Loading which is a child of Animated Buttons.
Button animation with loading right 
Issue: Fix for Inconsistent loading button labels #1075
Fixed labels for buttons with loading animation. Button with loading animation on left side are labeled "loading left", and those on the right side are labeled "loading right".
=> Fix for Inconsistent loading button labels #1075

dist/sbuttons.css, src/_variables.less, src/components/animated/_arrow.less
Fix #1018
1. Currently the arrow on the button appears using the `rotateY` transformation. Perhaps this is precisely why a strange vertical line appeared on the screenshot [in the issue description](https://github.com/sButtons/sbuttons/issues/1018). I've used the `opacity` property instead. It has fewer pitfalls.
2. Noticed that the edge of the word on the button blinks on hover. This is because the pseudo-element with an arrow first covers a part of the word, and then moves to the side. To fix this, I placed the pseudo element outside of the button. There it is invisible thanks to the `overflow` property of the button. Now on hover the button becomes wider and the arrow drives inward.
3. Removed a large piece of code regarding the background, color and shape of the pseudo-elements. The …
=> Fix #1018. Improve the "Next" and "Previous" buttons

dist/sbuttons.css, src/components/_basic.less, src/components/animated/_diagonalBackground.less, src/components/animated/_fill.less, src/components/animated/_ripple.less
Issue: #1014 
Please see the demo below. The solution I found for black-btn is to add a grey shadow so that it stands out a bit more than just plain black color. Please let me know if you have a better idea.
=> Add Dark Mode Support for Diagonal Background, Fill, and Ripple

assets/js/buttons-examples.js
Issue:
Buttons that had 3 or more classes weren't displayed correctly.
Each button should be preceded with a `.` but buttons that have more than 3 classes only has a `.` before the first three class names.
=> Fixing buttons that have more than 3 classes

CONTRIBUTING.md
As mentioned in an update in #1014, it is not required to add the dark mode media query to the buttons. So, the corresponding requirement in CONTRIBUTING.md needs to be removed.
=> Remove an outdated requirement from Contributing page

dist/sbuttons.css, src/components/icon/_icon-btn.less
Dark mode handling was added to Base Icon with transparent background.
Light mode:
Dark mode:
Issue: #1014
=> Add dark mode support for base icon

documentation.html
To fix the scroll issue, I simply replaced "#" with "#!". I did this instead of replacing it with the id of its container in order to make the page not scroll at all, as long as there is no other element on the page named "!". 
Issue: When clicking the download CSS link on the documentation page, page would scroll to the top. #1239
=> Download link scroll

assets/css/documentation.css, documentation.html
Added some text padding to text that appears underneath buttons on the documentation page. 
To do so, I created another CSS class called text-under-button, then changed the classed of the desired texts to text-under-button.  #1242 
Issue: Some text on the documentation page required some padding from the button above it.
=> Text padding

assets/css/documentation.css, documentation.html
Replace br elements with padding on the documentation page.
Issue: #1246
=> replace br element with margin on documentation

documentation.html
Issue: In the documentation page under Icon with no background change the class of the example button from base-icon-btn to icon-btn. This should be changed in the button and the code example
=> documentation issue- icon without bg

documentation.html
Issue: In the documentation page under Modify Button Colors the link to the variables file goes to sbuttons.less instead. The text should be changed to "_variables.less" and the link as well.
=> Modifycolor

examples.html
Moved Loader below Heading "Some Examples Of sButtons" in Example Page
Issue: Move Loader in Examples Page below heading #1257
=> Loader moved below heading in example page

dist/sbuttons.css, src/components/styles/_rounded-bottom.less
Added `transition: all 0.2s` to rounded-bottom button
Issue: #1262
=> Added transition to rounded-bottom button

dist/sbuttons.css, src/components/styles/_rounded-diagonal-tl.less, src/components/styles/_rounded-diagonal-tr.less
Added `transition: all 0.2s` to rounded-diagonal button, both top-left and top-right
Issue: #1263
=> Added transition to rounded-diagonal buttons

assets/css/main.css
Issue: Sidebar behavior before scroll #1258
Changes done: Removed "- 5vw" in navbar scrolling effect from main.css, now sidebar's width won't get reduced on scrolling.
=> sidebar issue solved, issue: #1258

documentation.html
Issue: Space should be placed after ".", not before
=> Fix punctuation typo in the documentation

package.json
Reduce published npm package size from __150.5 kB__ to __51.8 kB__ by using ["files" field](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files) in `package.json`.
Only folders and files that likely `required` by users are included, thus `src/` and `dist/`. Note that important files like `package.json` and `README.md` are automatically included by npm, so no need to explicitly include them.
[This](https://www.diffchecker.com/Qtlnw3F7) shows the comparison of files published before and after using "files" field.
=> Removes unnecessary files in published package

documentation.html, examples.html
In this PR I have changed the link of Examples in the footer section of the documentation and examples page to point to the examples page of our website rather than to the Github repo of our project.
Issue: Footer link problem #1336
=> Footer Link Problem Solved

README.md
Added a link in README.md file which leads to CSS file.
Issue: The `Download` button in the website doesn't download the file, instead it leads to the file, and so as the link added in the README because I took the link address from there.
=> Added CSS download link in README file. Fix for 1418

website/src/pages/Home/index.js
The brand name in the first sentence of the first paragraph on the home page is misspelled.
In the sentence, `Install sButttons’s source LESS via npm.`, the brand name is incorrectly spelled with three t's.
The sentence should read, `Install sButtons’s source LESS via npm.`, with the brand name correctly spelled with two t's.
Issue:
=> Fix typo in brand name on home page
